registries:
 - platform: 
   image-url: 
   registry-url: 
   username: 
   password: 
   repository: 

image-name: 
 
iterations: 

storage-url: 

image-generation:
  img-size-mb: 
  layer-number: 
  generate-random: 
  